Fix some spelling mistakes in the main README and make the verbage a little more consistent
Erotemic/sm64-random-assets pull request #6
Opened 2024-10-14 22:41 UTC by Multi-Volt

This project is super cool! I noticed a few issues in the read-me so I went ahead and took a pass at reviewing it and fixed some mistakes I found in the language. Hope this helps!

2024-10-14 23:34 UTC, Erotemic commented
Thanks, the first line I'd like to tweak, but everything else looks great!

2024-10-14 23:35 UTC, Erotemic requested changes
Just want to change this first line, everything else looks good.

2024-10-14 23:35 UTC, Erotemic commented on README.rst
> -Generates non-copyrighted randomized assets so sm64 and sm64-port can be used
This original line is correct. I wanted to reference the names of the repo. We can put them in backticks to codify them if you think that looks better.

2024-10-14 23:56 UTC, Multi-Volt commented
> Just want to change this first line, everything else looks good.

I added backticks with embedded hyperlinks to the repositories already present in the repository. I think this could make things easier to digest/access. Let me know your thoughts!

2024-10-15 00:39 UTC, Erotemic commented
I agree these are all improvements. Thanks!

2024-10-15 00:39 UTC, merged